### ISSUE TITLE
Add Share

### ISSUE THREAD

**Issue by BellangerSebastien** [Lens-Garden/lensgarden-interface#1]
Name: Share
Description: Share is a Web3 social writing platform where authors can publish books/webtoon/articles as NFT and readers can interact with their favorite authors.
Thumbnail URL: https://d2x76rid835axn.cloudfront.net/image/Share-01.png
Category: Social Writing 
Project URL: theshr.xyz

**Comment by saurabhdoteth** [comment]
@BellangerSebastien a size of 512px x 512px is recommended for thumbnail.

**Comment by BellangerSebastien** [comment]
Heyy, 

the new image : https://shr-dev.s3.eu-west-3.amazonaws.com/image/thumblensverse.png

Thanks :)

**Comment by saurabhdoteth** [comment]
@BellangerSebastien added under `Other` category for now
