### ISSUE TITLE
Add Huddle01

### ISSUE THREAD

**Issue by serg0x** [Lens-Garden/lensgarden-interface#6]
Name: Huddle01
Description: web3 video meetings and decentralized-RTC (dRTC) infrastructure.
Thumbnail URL: https://pbs.twimg.com/profile_images/1559528697652477952/V1NBeO88_400x400.jpg
Category: Video
Project URL: https://huddle01.com/

**Comment by saurabhdoteth** [comment]
added under `Communication Tool` category

**Comment by serg0x** [comment]
@saurabhdoteth could you please change Description to:

Description: web3 video meetings and infrastructure.

Thank you!
